site_name: akebono Doc 
theme: material
markdown_extensions:
  - codehilite
repo_url: https://github.com/risuoku/akebono
edit_uri: blob/master/_mkdocs/docs
use_directory_urls: false
pages:
- 'HOME': 'index.md'
- 'hello': 'notebooks/hello.md'
