site_name: akebono documentation
theme: material
markdown_extensions:
  - toc:
      permalink: true
  - codehilite
  - def_list
repo_url: https://github.com/risuoku/akebono
edit_uri: blob/master/_docsorigin/docs
use_directory_urls: false
nav:
- 'akebonoをはじめる': 'index.md'
- 'akebonoの設定': 'config.md'
- 'akebonoの構成': 'system.md'
- 'チュートリアル': 
  - '２つ以上の設定を一度に実行する': 'tutorials/1.md'
- 'APIリファレンス': 'sphinxapidocs/index.html'
