site_name: akebono documentation
theme: material
markdown_extensions:
  - toc:
      permalink: true
  - codehilite
  - def_list
repo_url: https://github.com/risuoku/akebono
edit_uri: blob/master/_docsorigin/docs
use_directory_urls: false
nav:
- 'HOME': 'index.md'
- 'hello': 'notebooks/hello.md'
- 'APIリファレンス': 'sphinxapidocs/index.html'
